# Generated by Django 2.0.2 on 2018-04-03 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0002_auto_20180402_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='AuthoredBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored', to='my_books.Author')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AddField(
            model_name='authoredbook',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored', to='my_books.Book'),
        ),
    ]
