# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-03 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0003_auto_20180403_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authoredbook',
            old_name='author_code',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
