# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-03 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0005_auto_20180403_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ForeignKey(default='tobe_added_later', on_delete=django.db.models.deletion.CASCADE, to='my_books.Book'),
            preserve_default=False,
        ),
    ]
