# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-12 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0006_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(to='my_books.Book'),
        ),
        migrations.AlterField(
            model_name='authoredbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='my_books.Book'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name'], name='my_books_au_name_1f9161_idx'),
        ),
    ]
